# Generated by Django 3.1.14 on 2025-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_robot_column_robot_direction_robot_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='is_temporary',
        ),
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
