# Generated by Django 3.1.14 on 2025-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20250410_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
